---
title: "Read Data From Web"
author: "Yuying Lu (yl5839)"
date: "2024-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```

```{r}
marj_use_df = 
  drug_use_html |>
  html_table() |> 
  first()

head(marj_use_df)
```

To delete the first row

```{r}
marj_use_df = 
  drug_use_html |>
  html_table() |> 
  first() |> 
  slice(-1)

head(marj_use_df)
```



```{r}
second_tbl_df = 
  drug_use_html |>
  html_table() |> 
  nth(2) |> 
  slice(-1)
  
head(second_tbl_df)

```



```{r}
url = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"
nyc_living_html = read_html(url)

nyc_living_df = 
  nyc_living_html |>
  html_table(header = TRUE) |> 
  first()
  
head(nyc_living_df)

```


## Get information not in a table


```{r}
swm_url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(swm_url)

title_vec = 
  swm_html |>
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |>
  html_text()

metascore_vec = 
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    score = metascore_vec,
    runtime = runtime_vec)

```

## Use API 

Get water data

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv")
nyc_water
nyc_water |> content()
```

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") |> 
  content("text") |>
  jsonlite::fromJSON() |>
  as_tibble()
```



Get BRFSS data

```{r}
water_API = 'https://chronicdata.cdc.gov/resource/acme-vg9e.json'
brfss_smart2010 = 
  GET(water_API,
      query = list("$limit" = 5000)) |> 
  content("parsed")

```

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") |>
  content()

poke[["name"]]
```



